apiVersion: v1
kind: LimitRange
metadata:
  name: development-limits
spec:
  limits:
  - default:
      cpu: "1"
      memory: 512Mi
    defaultRequest:
      cpu: 200m
      memory: 256Mi
    min:
      cpu: 50m
      memory: 16Mi
    max: 
      cpu: "4"
      memory: 4Gi
    type: Container
